local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05 

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
  
  plugins:
  - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}